language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.13
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: python setup.py test
matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=1.4.5
    - python: 3.2
      env: DJANGO_VERSION=1.3.7
    - python: 3.3
      env: DJANGO_VERSION=1.4.5
    - python: 3.3
      env: DJANGO_VERSION=1.3.7
    - python: 3.4
      env: DJANGO_VERSION=1.4.5
    - python: 3.4
      env: DJANGO_VERSION=1.3.7
    - python: "pypy"
      env: DJANGO_VERSION=1.4.5
    - python: "pypy"
      env: DJANGO_VERSION=1.3.7
